### PR TITLE
Update conda-forge.yml

### PR DESCRIPTION
**Pull request by knaaptime**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by knaaptime** [comment]
@conda-forge-admin, please rerender

**Review by jGaboardi — APPROVED** [review]

**Comment by jGaboardi** [comment]
@knaaptime This OK to merge?

**Comment by knaaptime** [comment]
i dunno, im not sure if this does anything or if we also need to bump the build number. I'm just not sure why some packages (e.g. lib and momepy) update quickly and others (mapclassify, tobler) don't. Could just be slow machinery at the moment

**Comment by jGaboardi** [comment]
> i dunno, im not sure if this does anything or if we also need to bump the build number. I'm just not sure why some packages (e.g. lib and momepy) update quickly and others (mapclassify, tobler) don't. Could just be slow machinery at the moment

@ocefpaf & @martinfleis Any thoughts on this?

**Comment by martinfleis** [comment]
Lib and momepy updated quickly because I have manually initiated those. This PR makes no difference to the update process. If you want to start an update, open an issue with `@conda-forge-admin, please update version` like this one https://github.com/conda-forge/momepy-feedstock/issues/36.

**Comment by knaaptime** [comment]
thanks, couldnt find that command

**Comment by martinfleis** [comment]
@knaaptime see https://conda-forge.org/docs/maintainer/infrastructure/#admin-web-services

**Pull request closed without merging**
