### PR TITLE
release for v2.6.0

### LINKED ISSUE #21: need `v2.6.0` release
Looks like this recipe was never re-rendered from [`v2.5.0`](https://github.com/conda-forge/mapclassify-feedstock/blob/11f01eb8929ce6c6f8d1d2ace7813a40d8701eb5/recipe/meta.yaml#L1) and released following the [`v2.6.0`](https://github.com/pysal/mapclassify/releases/tag/v2.6.0) release.

### PR DESCRIPTION
**Pull request by jGaboardi**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This PR resolves #21 .

### CODE REVIEW

**Comment by jGaboardi** [comment]
@conda-forge-admin, please rerender

**Comment by jGaboardi** [comment]
@conda-forge-admin, please rerender

**Comment by jGaboardi** [comment]
cc @martinfleis & @knaaptime

**Comment by martinfleis** [comment]
That is strange that the bot didn't pick it up.

**Comment by ocefpaf** [comment]
> That is strange that the bot didn't pick it up.

There isn't even an error in the status page :-/

https://conda-forge.org/status/#version_updates

**Comment by jGaboardi** [comment]
I think this is good to merge though, right?

**Comment by martinfleis** [comment]
Yes

**Comment by jGaboardi** [comment]
@ocefpaf Do you have time for a review + merge here?

**Comment by ocefpaf** [comment]
The requirements.txt file has:

```
scipy>=1.0
numpy>=1.3
scikit-learn
pandas>=1.0
networkx
```

everything in here has higher lower bounds. While that is fine it would be nice to open an issue upstream if those different  versions are needed.

**Comment by jGaboardi** [comment]
@ocefpaf Are you looking at the [`pyproject.toml`](https://github.com/pysal/mapclassify/blob/main/pyproject.toml)?

**Comment by ocefpaf** [comment]
> @ocefpaf Are you looking at the [`pyproject.toml`](https://github.com/pysal/mapclassify/blob/main/pyproject.toml)?

Nope. The requirements.txt. I guess you can open an issue upstream to remove the setup.py and the req files then.

**Comment by knaaptime** [comment]
@jGaboardi the last [released version of mapclassify](https://github.com/pysal/mapclassify/releases/tag/v2.6.0) is 2.6, and that still includes all the old stuff with setup.py, requirements.txt. etc

so the recipe here should match the requirements.txt in that tarball until we do a new release

**Comment by jGaboardi** [comment]
Ah, ha! I had thought we cut another `mapclassify` release already 😖

**Comment by jGaboardi** [comment]
@knaaptime should we a cut a `v2.6.1` then? or just let this ride? I'd vote for a `v2.6.1`.

**Comment by knaaptime** [comment]
im cool with a small bugfix release

**Comment by jGaboardi** [comment]
> im cool with a small bugfix release

On it.

**Comment by jGaboardi** [comment]
Done should be coming down the pipe in the next several hours.

**Pull request merged**
